### ISSUE TITLE
CentOS Implied but not explicit, /linux/ sustainable?

### ISSUE THREAD

**Issue by JWDT** [ans-group/docs.ukfast.co.uk#210]
Is the structure of /operatingsystems/linux/$programme sustainable?

Since UKFast -- especially in the cloud side of things -- offer Ubuntu & Debian, as well as CentOS & RHEL, would it make sense to divide /operatingsystems/linux into ../linux/centos, ../linux/ubuntu etc.? Even if it just had ../centos for now, that, and a bit of text in the introduction explicitly stating the OS that article is for could help avoid confusion for someone who might get very confused when they're told that 'yum' isn't installed and that they have to install it using apt (or apt-get).

**Comment by garryprior** [comment]
thanks for the suggestion John.  

It's a bit above my level of knowledge / expertise so I'll defer to @laf for comment?
