### ISSUE TITLE
Adding meta content to files

### ISSUE THREAD

**Issue by garryprior** [ans-group/docs.ukfast.co.uk#238]
@danHavercroft is taking on the challenge of adding meta content to files across docs.ukfast.  This issue is to track progress and record which files have meta added.

**Comment by garryprior** [comment]
Files are being tracked here
https://docs.google.com/spreadsheets/d/1JQQCKIxcc0iSwE8Y9hd0OutuzWTBLdpXY5TUqKTmyDA/edit#gid=0

**Comment by garryprior** [comment]
all done, thanks @danHavercroft and @will-marley

**Comment by garryprior** [comment]
are you able to continue with pages across the other categories @danHavercroft @will-marley ?

:-)

**Comment by will-marley** [comment]
I’ll get cracking whenever I have a minute ☺

**Comment by garryprior** [comment]
@danHavercroft @will-marley : chaps, I've added two new tabs to the Google spreadsheet - one is "Everything Else" - 134 files, the other is "Index files (.rst) - 62 files.
https://docs.google.com/spreadsheets/d/1JQQCKIxcc0iSwE8Y9hd0OutuzWTBLdpXY5TUqKTmyDA/edit#gid=0

I need to check the meta content works the same on .rst files, so if you get cracking on the "Everything Else" files for now that would be great.

**Comment by will-marley** [comment]
Sounds good, I’ve got some time to work on this tomorrow so will get cracking!

**Comment by garryprior** [comment]
@danHavercroft for the index.rst files there is no need to add the initial ` ```eval_rst` at the start of the meta content code (because the file itself is already in .rst format).  Other than that, it should look exactly the same - example below:

```
  .. meta::
     :title: How to map a network share | UKFast Documentation
     :description: A guide to mapping a network share on Windows 
     :keywords: ukfast, windows, network, share, mapping, drive, cloud, server
```

So you're good to go on the index.rst pages also :-)

**Comment by garryprior** [comment]
@danHavercroft I have booked out some time Tuesday morning to work through approvals (just wanted to let you know I haven't forgotten...)
