### ISSUE TITLE
Page under wrong breadcrumb catagory

### ISSUE THREAD

**Issue by devfoxnet** [ans-group/docs.ukfast.co.uk#267]
This page, https://docs.ukfast.co.uk/security/ddos/gettingstarted.html  sits under a different breadcrumb category (on the left of the page) than all the others below the DDoS section (e.g. https://docs.ukfast.co.uk/security/ddos/remove.html)

**Comment by garryprior** [comment]
this is because the same page is also relevant for Content Delivery Network, and we couldn't figure out a way of having it under both sections.  Happy to take suggestions on this @devfoxnet if you have any ideas?

**Comment by garryprior** [comment]
this has now been fixed @devfoxnet , so closing issue
