### ISSUE TITLE
DDoSX/Getting Started Process Updates

### ISSUE THREAD

**Issue by sam-metcalfe** [ans-group/docs.ukfast.co.uk#280]
security/ddos/gettingstarted needs a few updates to bring this into line with current setup process and interface, including up-to-date screenshots. Am planning to do this today.

**Comment by garryprior** [comment]
thanks @sam-metcalfe

**Comment by garryprior** [comment]
@sam-metcalfe the Getting Started on DDoSX docs have been updated in line with the WAF on DDoSX launch, I think this issue can now be closed unless you can see anything else that's out of date and/or inaccurate or confusing?

**Comment by garryprior** [comment]
closing this issue as I think it's broadly up to date now.
