### ISSUE TITLE
Purchasing and renewing SSL certificates - Updates Required

### ISSUE THREAD

**Issue by sam-metcalfe** [ans-group/docs.ukfast.co.uk#281]
.../Domains/ssl/buying.html displays incorrect subtitle in search screen and requires content updates to reflect changes made to validation process with Comodo certs. 

'Subtitle' currently displays "```eval_rst.". Looks like this is generated based on first paragraph of body content on the page so will just need something in there prior to the first header perhaps?

**Comment by garryprior** [comment]
good spot @sam-metcalfe , Looking at the page I don't think that section needs to be highlighted as a "note", so we could simply remove the rst formatting and have it as regular text.

Are you able to make the relevant content changes based on the latest validation process?

**Comment by garryprior** [comment]
does this still need updating @sam-metcalfe ?

**Comment by sam-metcalfe** [comment]
@garryprior It does indeed. I'll get on it.

**Comment by garryprior** [comment]
addressed in #350, now live

thanks @sam-metcalfe
