### ISSUE TITLE
Email should moved higher in the layout

### ISSUE THREAD

**Issue by thatdamndog** [ans-group/docs.ukfast.co.uk#314]
While, yes, most email servers do run on Linux so it's not technically incorrect to have it under OS>Linux,... With the shear number of customers who have issues with email, my gut feeling is that mail deserves to have a more accessible section on the front page. 

Thoughts?

**Comment by garryprior** [comment]
yes that makes sense. not sure email warrants a top-level billing though.  My plan is to remove Webcelerator from the top-level and put it under Networking along with CDN.  That will free up a space which can be replaced with a general "Hosting Guidance" section to include things like email, Wordpress etc.  There's a lot of stuff currently under Linux that fits better elsewhere!

thanks for getting stuck in @thatdamndog

**Comment by thatdamndog** [comment]
No worries! Are we limited to 9 top-level sections? Might be nice to have more (less clicks for users to find what they need). Things I can think of: Email, split OSes into their own Linux and Windows sections, put control panels in their own sections...  I'm a fan of keeping site navigation as flat as possible, in case that's not clear. :D

Hosting Guidance does fit better for general stuff that doesn't quite fit elsewhere. Looking forward to it.

**Comment by garryprior** [comment]
not limited to 9 sections, but the homepage currently has a 3x3 grid, so we'd need to add another three sections to maintain 3 across i.e 3 columns by *4* rows.

**Comment by thatdamndog** [comment]
That's fair. Remove Webcelerator makes 8. Add Linux, Windows, Email and Hosting Guidance sections makes 12?

**Comment by thatdamndog** [comment]
Doing some proper planning on what sections I'd suggest. We could also find some more suitable font icons for the top sections. I appreciate this will probably mean reworking the current layout class grid-container but if we're changing the existing loop up anyway to create a 3*4 layout, it might not be too much more work to make it look swish: 

Cloud - fa fa-cloud
Desktop + office - fa fa-desktop
Security - fa fa-lock (or fa fa-key, but I vote lock)
Domains + DNS - fa fa-random
Backups - fa fa-life-saver
High Availability - fa fa-globe
Networks - fa fa-sitemap
Monitoring - fa fa-heartbeat
Windows - fa fa-windows
Linux - fa fa-linux
Mail - fa fa-envelope
General - fa fa-wrench

12 sections and an appropriate icon for each. Thoughts?

**Comment by garryprior** [comment]
@thatdamndog moving this conversation internally as Ben Wilson is doing some work on the back end of docs.ukfast which can help.  

I will tag you on the issue.
