### ISSUE TITLE
Extend flex/general/accesslinuxinstances.md for linux/mac instructions

### ISSUE THREAD

**Issue by ghost** [ans-group/docs.ukfast.co.uk#335]
This guide covers windows instructions but it would be good to extend this with instructions for linux and mac based OS's. Only needs to be generic for linux, doesn't need to include how to download ssh-keygen etc.

**Comment by garryprior** [comment]
this article should be moved under the eCloud Flex instances category here 
https://docs.ukfast.co.uk/cloud/flex/nova/

rather than stay under General
