### ISSUE TITLE
Ambiguous Search Result Page Titles

### ISSUE THREAD

**Issue by sam-metcalfe** [ans-group/docs.ukfast.co.uk#341]
As an example, searching for 'cache', the top result is a page entitled 'Caching Rules' ( https://docs.ukfast.co.uk/network/cdn/cachingrules.html ). The first sentence of the body text in this instance is sufficient for working out the result's context but this may not always be the case. I would suggest either:

1) We specify explicitly that sufficient context is given in that first sentence in the Style Guide.

or

2) Update the Search to include a category breadcrumb with each search result

**Comment by garryprior** [comment]
Search overall needs a good look / overhaul.  Many terms don't return any links even though there are loads of articles.  For example typing Flex into the top search bar shows "no matches" until you hit Enter.

@BenWUKFast this should be another requirement for the rebuild
