### ISSUE TITLE
https://docs.ukfast.co.uk//security/firewalls

### ISSUE THREAD

**Issue by thatdamndog** [ans-group/docs.ukfast.co.uk#353]
Link to the firewalls section is ded: 

https://docs.ukfast.co.uk//security/firewalls

Might be my bad

**Comment by garryprior** [comment]
this is the firewalls section that we removed in #340 

unfortunately we don't have any kind of link forwarding on docs at present.  so if you spot this link in another page please update it to https://docs.ukfast.co.uk/network/firewalls/

**Comment by thatdamndog** [comment]
Oops, so it is. 

I had the page cached in my browser so the ded link was still there, and I was tired. My bad!
