### ISSUE TITLE
Tab search in chrome takes you to CakePHP docs

### ISSUE THREAD

**Issue by terencesimms** [ans-group/docs.ukfast.co.uk#671]
Hi,

In Chrome, when you type the url and hit tab, this shows the following, and takes you to the cakePHP docs.

![docs1](https://user-images.githubusercontent.com/3035178/88521858-7546e280-cfed-11ea-98a3-f5a9e1a6e0a4.PNG)

![docs2](https://user-images.githubusercontent.com/3035178/88521864-7710a600-cfed-11ea-9cb9-0f0b2c2122e4.PNG)

Expected behaviour would be to default to docs.ukfast.co.uk search.

**Comment by darrentayloruk** [comment]
This was fixed recently, try a cache refresh and it should work

**Comment by darrentayloruk** [comment]
https://github.com/ukfast/docs.ukfast.co.uk/pull/664
