### ISSUE TITLE
Subheading formatting

### ISSUE THREAD

**Issue by terencesimms** [ans-group/docs.ukfast.co.uk#704]
I've noticed that when using a subheading, it currently looks to blend into the document text, as below

three hash subheadings '###'
![image](https://user-images.githubusercontent.com/3035178/92592750-fb667200-f297-11ea-9a4f-220a54f05340.png)

![image](https://user-images.githubusercontent.com/3035178/92593133-834c7c00-f298-11ea-89d7-588ea0370868.png)

As we tend not to include a TOC tree at the top of a doc or at the sidebar for articles (unless explicitly specified in a unique index TOC with a tree depth of more than 1), it can be hard to know what is a subheading beyond hovering for a #link icon or knowing the syntax implies a heading.  Perhaps emboldening these subheadings would help.

**Comment by miff2000** [comment]
I think I've just fixed this issue. I've increase the `h3` font size from `1em` to `1.2em`. It looks better on this page at least, I think:

* https://docs.ukfast.co.uk/build/enterprise_backups.html
