### ISSUE TITLE
tests.sh fails markdown documents that aren't going to be published

### ISSUE THREAD

**Issue by Xiol** [ans-group/docs.ukfast.co.uk#938]
### What is the issue?

`tests.sh` fails Markdown documents which aren't going to be part of the published document set, e.g. README or contribution documents in the root of the repository.

### Steps To Reproduce

* Create a new Markdown document, extension `.md`, that isn't going to be part of the published document set.
* CI/CD will fail due to `tests.sh` failing checks on the new document.
* This can also be tested manually by running `./tests.sh ./doc.md`

Example: https://github.com/ukfast/docs.ukfast.co.uk/pull/937

### Expected behaviour

`tests.sh` should only check Markdown documents which are going to be a part of the published document set. The checks contained within are irrelevant for Markdown documents that won't be parsed by Sphinx.

### Possible fixes

`tests.sh` should ignore files outside of the `source/` directory, or the Github Workflow that gathers a list of changed files should be adjusted so it only examines files within `source/` - this latter option may have unintended consequences so needs further investigation.

The list of files passed to `tests.sh` is gathered by the CI/CD workflow [here](https://github.com/ukfast/docs.ukfast.co.uk/blob/9810cf6582d35ae72be40168fb084fead11e1b77/.github/workflows/test.yaml#L10-L28), so without changing that, `tests.sh` must expect to receive files from anywhere in the repository.

**Comment by mohitsaxenaknoldus** [comment]
I've done something very similar to this a few days back. I'll do it, you can assign it to me.
