### ISSUE TITLE
Search Function Inoperable

### ISSUE THREAD

**Issue by terencesimms** [ans-group/docs.ukfast.co.uk#979]
### What is the issue?

The search function/autocomplete in docs looks to be inoperable, and isn't suggesting anything. Same thing happening with myukfast pss creation subject autocomplete.

### Steps To Reproduce

docs.ukfast.co.uk

Search for anything, and autocomplete doesn't return anything

Same for the ticket creation subject within myukfast pss creation.
https://my.ukfast.co.uk/pss/create

![image](https://user-images.githubusercontent.com/3035178/170203317-954131f4-3532-4014-b3df-feaf053e1dfa.png)

### Expected behaviour

Typing in the search field in docs returns a set list of suggestions based on the word/letters typed

**Comment by 0x4c6565** [comment]
Restarted deployment, populator has now re-ran. I can see search functionality is now working.

This was caused by https://github.com/ukfast/docs.ukfast.co.uk/pull/978
